### ISSUE TITLE
Keras 2

### ISSUE THREAD

**Issue by mas-dse-greina** [radioML/examples#1]
Tim,

Is there an update to the iPython notebook for Keras v. 2? I'm getting several errors with the current code.

Thanks.
-Tony

**Comment by mas-dse-greina** [comment]
I've corrected the errors and put an updated version here: https://github.com/mas-dse-greina/examples/blob/master/modulation_recognition/RML2016.10a_VTCNN2_example.ipynb

**Comment by xwshan** [comment]
> I've corrected the errors and put an updated version here: https://github.com/mas-dse-greina/examples/blob/master/modulation_recognition/RML2016.10a_VTCNN2_example.ipynb
What is the version of the key library? Keras，numpy，python ......
